---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-value-overrides
  namespace: ns-postgresql
data:
  values.yaml: |-
    auth:
      postgresPassword: secretpassword
    global:
      storageClass: sc-postgresql
    primary:
      persistence:
        storageClass: sc-postgresql
        size: 400Mi
    volumePermissions:
      enabled: true
