---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-hr
  namespace: ns-postgresql
spec:
  chart:
    spec:
      chart: "bitnami/postgresql"
      version: 12.8.2
      sourceRef:
        kind: GitRepository
        name: git-bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: postgresql-rn
  valuesFrom:
  - kind: ConfigMap
    name: postgresql-value-overrides
    valuesKey: values.yaml
