---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-postgresql
 namespace: ns-postgresql
spec:
  storageClassName: sc-postgresql
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv-postgresql"