---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-hr
  namespace: test-grafana
spec:
  chart:
    spec:
      chart: ""
      version: 9.x
      sourceRef:
        kind: HelmRepository
        name: my-release-grafana
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: grafana-releasename
  valuesFrom:
  - kind: ConfigMap
    name: grafana-helm-value-overrides
    valuesKey: values.yaml