---
apiVersion: v1
kind: Namespace
metadata:
  name: test-grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-helm-value-overrides
  namespace: test-grafana
data:
  values.yaml: |-
    # chart values to override.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-hr
  namespace: test-grafana
spec:
  chart:
    spec:
      chart: grafana
      version: 9.x
      sourceRef:
        kind: HelmRepository
        name: my-release-grafana
        namespace: default
  interval: 15m
  timeout: 5m
  releaseName: grafana-releasename
  valuesFrom:
  - kind: ConfigMap
    name: grafana-helm-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity