---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-hr
  namespace: ns-prometheus
spec:
  chart:
    spec:
      chart: "bitnami/prometheus"
      version: 0.1.10
      sourceRef:
        kind: GitRepository
        name: git-bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: prometheus-rn
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-value-overrides
    valuesKey: values.yaml
