---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-hr
  namespace: ns-grafana
spec:
  chart:
    spec:
      chart: "bitnami/grafana"
      version: 9.0.5
      sourceRef:
        kind: GitRepository
        name: git-bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: grafana-rn
  valuesFrom:
  - kind: ConfigMap
    name: grafana-value-overrides
    valuesKey: values.yaml
