---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-grafana
 namespace: ns-grafana
spec:
  storageClassName: sc-grafana
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/pv/grafana"