---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-value-overrides
  namespace: ns-rmq
data:
  values.yaml: |-
    image:
      debug: true
    persistence:
      existingClaim: pvc-rmq
    volumePermissions:
      enabled: true
    clustering:
      enabled: false