---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-hr
  namespace: ns-rmq
spec:
  chart:
    spec:
      chart: "bitnami/rabbitmq"
      version: 12.0.10
      sourceRef:
        kind: GitRepository
        name: git-bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: rmq-rn
  valuesFrom:
  - kind: ConfigMap
    name: rabbitmq-value-overrides
    valuesKey: values.yaml
