---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rmq
  namespace: ns-rmq
spec:
  storageClassName: sc-rmq
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi