---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-value-overrides
  namespace: ns-mongodb
data:
  values.yaml: |-
    global:
      storageClass: sc-mongodb
    persistence:
      enabled: true
      storageClass: sc-mongodb
      size: 9Gi
    volumePermissions:
      enabled: true
