---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-hr
  namespace: ns-mongodb
spec:
  chart:
    spec:
      chart: "bitnami/mongodb"
      version: 13.16.3
      sourceRef:
        kind: GitRepository
        name: git-bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: mongodb-rn
  valuesFrom:
  - kind: ConfigMap
    name: mongodb-value-overrides
    valuesKey: values.yaml
