---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-mongodb
 namespace: ns-mongodb
spec:
  storageClassName: sc-mongodb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv-mongodb"