---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-value-overrides
  namespace: ns-hashicorpvault
data:
  values.yaml: |-
    global:
      storageClass: sc-hashicorpvault
    server:
      replicaCount: 1
      persistence:
        storageClass: sc-hashicorpvault
        size: 100Mi
    volumePermissions:
      enabled: true