---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault
  namespace: ns-hashicorp-vault
spec:
  storageClassName: sc-vault
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv/vault"