---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hashicorpvault
  namespace: ns-hashicorpvault
spec:
  storageClassName: sc-hashicorpvault
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv-hashicorpvault"