---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-hr-change
  namespace: ns-metallb
spec:
  chart:
    spec:
      chart: "bitnami/metallb"
      version: 0.13.10
      sourceRef:
        kind: GitRepository
        name: git-bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: metallb-rn
